version: "3.3"

services:
  static:
    container_name: ${CONTAINER_NAME}
    # build: .
    image: ${IMAGE}
    expose:
      - 80
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    environment:
      NODE_ENV: production
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_KEYSIZE: ${LETSENCRYPT_KEYSIZE: 2048}
networks:
  default:
    external:
      name: ${NETWORK}
